[theme]
inherit = pydata_sphinx_theme
stylesheet = styles/scverse.css
pygments_style = tango

[options]
repo =
package =
accent =
show_ecosystem_dropdown = True

navbar_align = left
navbar_start = navbar-logo
navbar_center = navbar-nav
navbar_end = scverse-ecosystem, theme-switcher, navbar-icon-links
navbar_persistent = search-button
secondary_sidebar_items = page-toc, edit-this-page, sourcelink
footer_start = scverse-footer
footer_center =
footer_end =
show_nav_level = 0
show_toc_level = 2
navigation_depth = 3
collapse_navigation = False
pygments_light_style = tango
pygments_dark_style = monokai
announcement = https://scverse.org/announcement.html
