"""The scverse package registry.

One mapping drives three things that used to be maintained separately in every repository: the "scverse packages"
navbar dropdown, the per-package accent colour, and `intersphinx_mapping`.

The data is generated by ``scripts/build_registry.py`` from `scverse/ecosystem-packages`_, so this module never
becomes a second place to edit package metadata.

.. _scverse/ecosystem-packages: https://github.com/scverse/ecosystem-packages
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal, TypedDict

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

__all__ = ["Package", "core_packages", "get", "intersphinx", "packages"]

_REGISTRY_PATH = Path(__file__).parent / "registry.json"


class _RegistryFile(TypedDict):
    core_intersphinx: list[str]
    external: dict[str, str]
    packages: dict[str, dict[str, Any]]


#: The brand primary, used when a package has no accent of its own.
DEFAULT_ACCENT = "#4557c4"


@dataclass(frozen=True, slots=True)
class Package:
    """One entry in the scverse package registry."""

    name: str
    """The package's display name, e.g. ``"scvi-tools"``."""

    kind: Literal["core", "ecosystem"]
    """Whether the package is maintained by the core team or listed as an ecosystem package."""

    docs: str
    """Where to send a reader, exactly as the upstream listing records it.

    This is a link for humans, so it may name a particular page rather than a documentation root.
    """

    inventory: str | None = None
    """Root URL under which the package's ``objects.inv`` resolves, or :data:`None` if it publishes no inventory.

    Distinct from :attr:`docs`: a versioned Read the Docs site serves its inventory and pages under ``en/stable/``
    or the like, while its documentation home is the bare domain.
    """

    repo: str | None = None
    """URL of the source repository, if the upstream listing records one."""

    description: str = ""
    """One-line summary, as recorded upstream."""

    accent: str = DEFAULT_ACCENT
    """The package's brand accent, falling back to the scverse primary."""


@cache
def _load() -> _RegistryFile:
    """Read and cache the generated registry file."""
    with _REGISTRY_PATH.open() as f:
        registry: _RegistryFile = json.load(f)
    return registry


@cache
def packages() -> Mapping[str, Package]:
    """Return every registered package, keyed by name.

    Returns
    -------
    A mapping from package name to :class:`Package`, ordered case-insensitively by name.
    """
    return {name: Package(**entry) for name, entry in _load()["packages"].items()}


def core_packages() -> Mapping[str, Package]:
    """Return only the core packages, in the order the website lists them."""
    return {name: pkg for name, pkg in packages().items() if pkg.kind == "core"}


def get(name: str) -> Package | None:
    """Look up a package by name, case-insensitively.

    Parameters
    ----------
    name
        The package name, e.g. ``"pertpy"``.

    Returns
    -------
    The registry entry, or :data:`None` if the package is not registered.
    """
    if (pkg := packages().get(name)) is not None:
        return pkg
    lowered = name.lower()
    return next((pkg for key, pkg in packages().items() if key.lower() == lowered), None)


def intersphinx(*extra: str, external: bool = True, core: bool = True) -> dict[str, tuple[str, None]]:
    """Build an `intersphinx_mapping` for this package.

    Deliberately not "every scverse package by default": each entry is an inventory fetched on every build, and all
    100+ of them would make a cold docs build slow and give it 100+ chances to fail on someone else's outage.
    The default is the handful of packages that almost every scverse docs build actually links to, and anything else
    is opted into by name.

    Parameters
    ----------
    extra
        Additional registry package names to include, e.g. ``intersphinx("scanpy", "muon")``.
        Unknown names raise, so a typo or a renamed package fails the build instead of silently dropping links.
    external
        Whether to include the non-scverse inventories (Python, NumPy, SciPy, pandas, Matplotlib).
    core
        Whether to include the default scverse inventories.

    Returns
    -------
    A mapping ready to assign to `intersphinx_mapping`.

    Raises
    ------
    KeyError
        If a name in `extra` is not in the registry.
    ValueError
        If a name in `extra` is registered but publishes no ``objects.inv`` to link against.

    Examples
    --------
    >>> mapping = intersphinx("scanpy")
    >>> mapping["scanpy"]  # doctest: +ELLIPSIS
    ('https://scanpy.scverse.org/...', None)
    """
    data = _load()
    mapping: dict[str, tuple[str, None]] = {}
    if external:
        mapping.update({name: (url, None) for name, url in data["external"].items()})

    names: Iterable[str] = (*(data["core_intersphinx"] if core else ()), *extra)
    for name in names:
        if (pkg := get(name)) is None:
            msg = f"{name!r} is not in the scverse registry. Known packages: {', '.join(sorted(packages()))}"
            raise KeyError(msg)
        if pkg.inventory is None:
            msg = f"{pkg.name} publishes no objects.inv at {pkg.docs}, so there is nothing to link against."
            raise ValueError(msg)
        # Key on the requested name so `:doc:`scanpy:...`` reads the way the author wrote it.
        mapping[name] = (pkg.inventory, None)
    return mapping
