#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# ///
"""Regenerate `scverse_doc/registry.json` from the upstream source of truth.

That source is `scverse/ecosystem-packages <https://github.com/scverse/ecosystem-packages>`_, which holds one
schema-validated ``packages/<Name>/meta.yaml`` per package.
Its published `packages.json`_ is that metadata already collated and resolved – including each package's
``inventory``, the documentation root whose ``objects.inv`` actually answers, which is not something the
``meta.yaml`` records.
The website renders its package pages from the same file.

Hand-maintaining a second list would guarantee it drifts from that one, so this script derives the registry
instead.
Only the per-package accent colours are curated here, because they live in the website's SCSS rather than in the
package metadata.

Usage
-----
    uv run scripts/build_registry.py

.. _packages.json: https://scverse.org/ecosystem-packages/packages.json
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

HERE = Path(__file__).parent
TARGET = HERE.parent / "src" / "scverse_doc" / "registry.json"

#: Cloudflare answers 403 to urllib's default agent, so ask as ourselves.
SOURCE = urllib.request.Request(
    "https://scverse.org/ecosystem-packages/packages.json",
    headers={"User-Agent": "scverse-doc registry build (+https://github.com/scverse/scverse-doc)"},
)

#: Brand accents, transcribed from ``assets/main.scss`` in the website repository.
#: These are not derivable from either package listing, so they are curated here and checked by
#: ``tests/test_registry.py`` against the SCSS when a checkout is available.
ACCENTS = {
    "anndata": "#e5864b",
    "mudata": "#4ab274",
    "muon": "#6cf1a1",
    "pertpy": "#da347f",
    "scanpy": "#de367b",
    "scirpy": "#da347f",
    "scvi-tools": "#fbb822",
    "spatialdata": "#40a9ff",
    "squidpy": "#969dea",
}

#: Upstream ``category`` -> the ``kind`` recorded here.
#: ``core-infrastructure`` is deliberately absent: those entries are scverse's own repositories (governance, stats,
#: the website) rather than packages, and the website's own listing skips them for the same reason.
KINDS = {
    "core-datastructure": "core",
    "core-framework": "core",
    "ecosystem": "ecosystem",
}

#: Non-scverse inventories that essentially every scverse package needs.
EXTERNAL = {
    "python": "https://docs.python.org/3",
    "numpy": "https://numpy.org/doc/stable/",
    "scipy": "https://docs.scipy.org/doc/scipy/",
    "pandas": "https://pandas.pydata.org/docs/",
    "matplotlib": "https://matplotlib.org/stable/",
}


def build() -> dict[str, Any]:
    """Build the registry mapping from the published upstream listing."""
    with urllib.request.urlopen(SOURCE) as response:
        upstream = json.load(response)

    packages: dict[str, dict[str, Any]] = {}
    for meta in upstream:
        if not (kind := KINDS.get(meta.get("category", ""))):
            continue
        name = meta["name"].casefold()
        entry = {
            "name": meta["name"],
            "kind": kind,
            "docs": meta["documentation_home"],  # verbatim: upstream picked this page for human readers
            "inventory": meta.get("inventory"),
            "repo": meta.get("project_home"),
            "description": " ".join(meta.get("description", "").split()),
        }
        if accent := ACCENTS.get(name):
            entry["accent"] = accent
        packages[name] = entry

    # Every core package is cross-linkable out of the box: they are the ones scverse docs actually link to, and
    # the ecosystem's hundred entries stay opt-in so a cold build does not fetch all 113 inventories.
    # Sorted, because upstream's own listing order is not stable and ``--check`` would flip on it.
    core = sorted(name for name, entry in packages.items() if entry["kind"] == "core" and entry["inventory"])
    return {
        "$comment": "GENERATED by scripts/build_registry.py – do not edit by hand.",
        "core_intersphinx": core,
        "external": EXTERNAL,
        "packages": dict(sorted(packages.items())),
    }


def main() -> int:
    """Write the regenerated registry to disk."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing if the output would change")
    args = parser.parse_args()

    registry = build()
    rendered = json.dumps(registry, indent=2, ensure_ascii=False) + "\n"
    if args.check:
        if TARGET.read_text() != rendered:
            print(f"{TARGET} is out of date; rerun scripts/build_registry.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(rendered)
    print(f"wrote {len(registry['packages'])} packages to {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
