#!/usr/bin/env python
"""Regenerate the light-mode brand tokens from the scverse website's SCSS.

The website is the brand's source of truth, so transcribing its hex values into this repository by hand would create
exactly the kind of drift this package exists to remove.
This script extracts the handful of SCSS variables that make up the brand and writes them out as CSS custom
properties.

Dark-mode tokens are *not* generated: the website has no dark mode at all, so there is nothing upstream to extract
and ``theme/scverse/static/scverse-dark.css`` is hand-authored design work instead.

Usage
-----
    python scripts/sync_brand_tokens.py --website ../scverse.github.io
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
TARGET = HERE.parent / "src" / "scverse_doc" / "theme" / "scverse" / "static" / "_tokens.css"

#: SCSS variable in ``assets/main.scss`` -> CSS custom property emitted here.
TOKEN_MAP = {
    "greyheader": "--scverse-color-heading",
    "navtext": "--scverse-color-text-secondary",
    "greydesc": "--scverse-color-text-muted",
    "tilebg": "--scverse-color-surface",
    "tilebg4": "--scverse-color-surface-alt",
    "overline": "--scverse-color-border",
    "backtickbg": "--scverse-color-code-bg",
    "backticktext": "--scverse-color-code-text",
    "footerbg": "--scverse-color-footer-bg",
}

#: Values that are written as literals in the SCSS rather than as variables, so they cannot be looked up by name.
#: Verified against ``assets/main.scss`` by :func:`check_literals`.
LITERALS = {
    "--scverse-color-primary": "#4557c4",
    "--scverse-color-gradient-start": "#262fb5",
    "--scverse-color-gradient-end": "#74c8fa",
}

_HEADER = """/*
 * GENERATED by scripts/sync_brand_tokens.py from scverse.github.io — do not edit by hand.
 *
 * Light-mode brand tokens only. Dark-mode overrides live in scverse-dark.css, which is hand-authored because the
 * website has no dark mode to extract one from.
 */
"""


def parse_scss(scss: str) -> dict[str, str]:
    """Extract top-level ``$name: #value;`` declarations from SCSS source."""
    return dict(re.findall(r"^\$([\w-]+):\s*(#[0-9a-fA-F]{3,8})\s*;", scss, re.MULTILINE))


def check_literals(scss: str) -> list[str]:
    """Return the literal token values that no longer appear in the SCSS.

    The primary and the gradient stops are written inline in the website's CSS rules, so they cannot be resolved by
    variable name.
    Checking that they still occur at all is a cheap guard against the brand changing underneath us.
    """
    return [f"{name} ({value})" for name, value in LITERALS.items() if value.lower() not in scss.lower()]


def render(scss: str) -> str:
    """Render the token stylesheet from SCSS source."""
    variables = parse_scss(scss)
    missing = sorted(set(TOKEN_MAP) - set(variables))
    if missing:
        msg = f"SCSS variables vanished from the website: {', '.join('$' + m for m in missing)}"
        raise KeyError(msg)

    lines = [_HEADER, ":root {"]
    lines += [f"  {prop}: {value};" for prop, value in LITERALS.items()]
    lines += [f"  {prop}: {variables[scss_name]};" for scss_name, prop in TOKEN_MAP.items()]
    lines += [
        "",
        "  /* Derived: the brand gradient used for hero surfaces and the active-nav underline. */",
        "  --scverse-gradient: linear-gradient(",
        "    135deg,",
        "    var(--scverse-color-gradient-start),",
        "    var(--scverse-color-gradient-end)",
        "  );",
        "",
        "  /* Typography: Inter is the website's typeface, self-hosted alongside the theme. */",
        '  --scverse-font-body: "Inter", -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;',
        '  --scverse-font-mono: "SFMono-Regular", Menlo, Consolas, "DejaVu Sans Mono", monospace;',
        "",
        "  /* Shared component geometry. */",
        "  --scverse-radius: 0.35rem;",
        "  --scverse-shadow: 0 0.15rem 0.5rem rgb(0 0 0 / 8%);",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """Write the regenerated token stylesheet to disk."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--website", type=Path, required=True, help="checkout of scverse/scverse.github.io")
    parser.add_argument("--check", action="store_true", help="fail instead of writing if the output would change")
    args = parser.parse_args()

    scss = (args.website / "assets" / "main.scss").read_text()
    if stale := check_literals(scss):
        print(f"literal brand colours no longer found in main.scss: {', '.join(stale)}", file=sys.stderr)
        return 1

    rendered = render(scss)
    if args.check:
        if TARGET.read_text() != rendered:
            print(f"{TARGET} is out of date; rerun scripts/sync_brand_tokens.py", file=sys.stderr)
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
